require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 120

RSpec/NamedSubject:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

